In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('student_raw_data.csv')
df

              Name  Age  Gender  Physics  Math  CS  English  History
0       Tre Taylor   19    Male       67    99  55       54       86
1      Kenny Brown   23  Female       90    83  94       91       96
2     Ray Anderson   22  Female       42    76  90       46       60
3  Makayla Johnson   21  Female       48    78  57       43       64
4       Tre Taylor   18  Female       99    53  89       97       48
5   Maddie Johnson   18  Female       65    92  41       59       67
6    Amiyah Taylor   20  Female       86    99  46       83       47
7     Tre Anderson   20  Female       86    74  53       56       75
8        Ray Smith   24  Female       89    79  43       41       45
9   Makayla Taylor   19    Male       93    81  43       93       68

## Data Understanding and Preparation

In [3]:
#Preview data
df.head() #first five rows of the data frame by default

              Name  Age  Gender  Physics  Math  CS  English  History
0       Tre Taylor   19    Male       67    99  55       54       86
1      Kenny Brown   23  Female       90    83  94       91       96
2     Ray Anderson   22  Female       42    76  90       46       60
3  Makayla Johnson   21  Female       48    78  57       43       64
4       Tre Taylor   18  Female       99    53  89       97       48

In [4]:
#Preview data
df.tail() #last five rows of the data frame by default

             Name  Age  Gender  Physics  Math  CS  English  History
5  Maddie Johnson   18  Female       65    92  41       59       67
6   Amiyah Taylor   20  Female       86    99  46       83       47
7    Tre Anderson   20  Female       86    74  53       56       75
8       Ray Smith   24  Female       89    79  43       41       45
9  Makayla Taylor   19    Male       93    81  43       93       68

In [5]:
df.shape

(10, 8)

In [6]:
df.size

80

In [7]:
df.columns

Index(['Name', 'Age', 'Gender', 'Physics', 'Math', 'CS', 'English', 'History'], dtype='object')

In [8]:
df.dtypes

Name       object
Age         int64
Gender     object
Physics     int64
Math        int64
CS          int64
English     int64
History     int64
dtype: object

In [9]:
df.info

<bound method DataFrame.info of               Name  Age  Gender  Physics  Math  CS  English  History
0       Tre Taylor   19    Male       67    99  55       54       86
1      Kenny Brown   23  Female       90    83  94       91       96
2     Ray Anderson   22  Female       42    76  90       46       60
3  Makayla Johnson   21  Female       48    78  57       43       64
4       Tre Taylor   18  Female       99    53  89       97       48
5   Maddie Johnson   18  Female       65    92  41       59       67
6    Amiyah Taylor   20  Female       86    99  46       83       47
7     Tre Anderson   20  Female       86    74  53       56       75
8        Ray Smith   24  Female       89    79  43       41       45
9   Makayla Taylor   19    Male       93    81  43       93       68>

In [10]:
df.isnull()

    Name    Age  Gender  Physics   Math     CS  English  History
0  False  False   False    False  False  False    False    False
1  False  False   False    False  False  False    False    False
2  False  False   False    False  False  False    False    False
3  False  False   False    False  False  False    False    False
4  False  False   False    False  False  False    False    False
5  False  False   False    False  False  False    False    False
6  False  False   False    False  False  False    False    False
7  False  False   False    False  False  False    False    False
8  False  False   False    False  False  False    False    False
9  False  False   False    False  False  False    False    False

In [11]:
df.isnull().sum()

Name       0
Age        0
Gender     0
Physics    0
Math       0
CS         0
English    0
History    0
dtype: int64

In [13]:
print(df.isnull().sum().sum())

0

In [15]:
df[['Name','Physics']] #must use two brackets when extracting two columns

              Name  Physics
0       Tre Taylor       67
1      Kenny Brown       90
2     Ray Anderson       42
3  Makayla Johnson       48
4       Tre Taylor       99
5   Maddie Johnson       65
6    Amiyah Taylor       86
7     Tre Anderson       86
8        Ray Smith       89
9   Makayla Taylor       93

In [16]:
df.info() #complete information

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     10 non-null     object
 1   Age      10 non-null     int64
 2   Gender   10 non-null     object
 3   Physics  10 non-null     int64
 4   Math     10 non-null     int64
 5   CS       10 non-null     int64
 6   English  10 non-null     int64
 7   History  10 non-null     int64
dtypes: int64(6), object(2)
memory usage: 772.0+ bytes

In [19]:
print(df['Gender'].unique())
print(df['Gender'].nunique())

['Male' 'Female']
2

In [22]:
print(df['Name'].unique())
print(df['Name'].nunique())

['Tre Taylor' 'Kenny Brown' 'Ray Anderson' 'Makayla Johnson'
 'Maddie Johnson' 'Amiyah Taylor' 'Tre Anderson' 'Ray Smith'
 'Makayla Taylor']
9

In [24]:
df['Name'].duplicated()

0    False
1    False
2    False
3    False
4     True
5    False
6    False
7    False
8    False
9    False
Name: Name, dtype: bool

In [25]:
df

              Name  Age  Gender  Physics  Math  CS  English  History
0       Tre Taylor   19    Male       67    99  55       54       86
1      Kenny Brown   23  Female       90    83  94       91       96
2     Ray Anderson   22  Female       42    76  90       46       60
3  Makayla Johnson   21  Female       48    78  57       43       64
4       Tre Taylor   18  Female       99    53  89       97       48
5   Maddie Johnson   18  Female       65    92  41       59       67
6    Amiyah Taylor   20  Female       86    99  46       83       47
7     Tre Anderson   20  Female       86    74  53       56       75
8        Ray Smith   24  Female       89    79  43       41       45
9   Makayla Taylor   19    Male       93    81  43       93       68