- Reading csv file
- creating new columns from existing
- filtering
- grouping

In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('student_raw_data.csv')
df

              Name  Age  Gender  Physics  Math  CS  English  History
0       Tre Taylor   19    Male       67    99  55       54       86
1      Kenny Brown   23  Female       90    83  94       91       96
2     Ray Anderson   22  Female       42    76  90       46       60
3  Makayla Johnson   21  Female       48    78  57       43       64
4       Tre Taylor   18  Female       99    53  89       97       48
5   Maddie Johnson   18  Female       65    92  41       59       67
6    Amiyah Taylor   20  Female       86    99  46       83       47
7     Tre Anderson   20  Female       86    74  53       56       75
8        Ray Smith   24  Female       89    79  43       41       45
9   Makayla Taylor   19    Male       93    81  43       93       68

In [3]:
df_new=df.copy()
df_new

              Name  Age  Gender  Physics  Math  CS  English  History
0       Tre Taylor   19    Male       67    99  55       54       86
1      Kenny Brown   23  Female       90    83  94       91       96
2     Ray Anderson   22  Female       42    76  90       46       60
3  Makayla Johnson   21  Female       48    78  57       43       64
4       Tre Taylor   18  Female       99    53  89       97       48
5   Maddie Johnson   18  Female       65    92  41       59       67
6    Amiyah Taylor   20  Female       86    99  46       83       47
7     Tre Anderson   20  Female       86    74  53       56       75
8        Ray Smith   24  Female       89    79  43       41       45
9   Makayla Taylor   19    Male       93    81  43       93       68

In [4]:
df_new['Age']

0    19
1    23
2    22
3    21
4    18
5    18
6    20
7    20
8    24
9    19
Name: Age, dtype: int64

In [6]:
#df_new['Total']=df_new['Physics']+df_new['Math']+df_new['CS']+df_new['English']+df_new['History']
df_new['Total']=df_new[['Physics', 'Math', 'CS', 'English', 'History']].sum(axis=1) #axis=1 is embedding a new column, axis=0 represents a row

In [7]:
df_new

              Name  Age  Gender  Physics  Math  CS  English  History  Total
0       Tre Taylor   19    Male       67    99  55       54       86    361
1      Kenny Brown   23  Female       90    83  94       91       96    454
2     Ray Anderson   22  Female       42    76  90       46       60    314
3  Makayla Johnson   21  Female       48    78  57       43       64    290
4       Tre Taylor   18  Female       99    53  89       97       48    386
5   Maddie Johnson   18  Female       65    92  41       59       67    324
6    Amiyah Taylor   20  Female       86    99  46       83       47    361
7     Tre Anderson   20  Female       86    74  53       56       75    344
8        Ray Smith   24  Female       89    79  43       41       45    297
9   Makayla Taylor   19    Male       93    81  43       93       68    378

In [11]:
df_new['Sci_total']=df_new[['Physics', 'CS']].sum(axis=1)

In [12]:
df_new

,Name,Age,Gender,Physics,Math,CS,English,History,Total,Sci_total
0,Tre Taylor,19,Male,67,99,55,54,86,361,122
1,Kenny Brown,23,Female,90,83,94,91,96,454,184
2,Ray Anderson,22,Female,42,76,90,46,60,314,132
3,Makayla Johnson,21,Female,48,78,57,43,64,290,105
4,Tre Taylor,18,Female,99,53,89,97,48,386,188
5,Maddie Johnson,18,Female,65,92,41,59,67,324,106
6,Amiyah Taylor,20,Female,86,99,46,83,47,361,132
7,Tre Anderson,20,Female,86,74,53,56,75,344,139
8,Ray Smith,24,Female,89,79,43,41,45,297,132
9,Makayla Taylor,19,Male,93,81,43,93,68,378,136

In [13]:
df_new['Percentage']=(df_new['Total']/500)*100
df_new

,Name,Age,Gender,Physics,Math,CS,English,History,Total,Sci_total,Percentage
0,Tre Taylor,19,Male,67,99,55,54,86,361,122,72.2
1,Kenny Brown,23,Female,90,83,94,91,96,454,184,90.8
2,Ray Anderson,22,Female,42,76,90,46,60,314,132,62.8
3,Makayla Johnson,21,Female,48,78,57,43,64,290,105,58.0
4,Tre Taylor,18,Female,99,53,89,97,48,386,188,77.2
5,Maddie Johnson,18,Female,65,92,41,59,67,324,106,64.8
6,Amiyah Taylor,20,Female,86,99,46,83,47,361,132,72.2
7,Tre Anderson,20,Female,86,74,53,56,75,344,139,68.8
8,Ray Smith,24,Female,89,79,43,41,45,297,132,59.4
9,Makayla Taylor,19,Male,93,81,43,93,68,378,136,75.6

In [14]:
def grade(Percentage):
    if Percentage >=90:
        return 'A'
    elif Percentage >=80:
        return 'B'
    elif Percentage >=70:
        return 'C'
    elif Percentage >=60:
        return 'D'
    else:
        return 'F'

In [15]:
df_new['Grade']=df_new['Percentage'].apply(grade)
df_new

,Name,Age,Gender,Physics,Math,CS,English,History,Total,Sci_total,Percentage,Grade
0,Tre Taylor,19,Male,67,99,55,54,86,361,122,72.2,C
1,Kenny Brown,23,Female,90,83,94,91,96,454,184,90.8,A
2,Ray Anderson,22,Female,42,76,90,46,60,314,132,62.8,D
3,Makayla Johnson,21,Female,48,78,57,43,64,290,105,58.0,F
4,Tre Taylor,18,Female,99,53,89,97,48,386,188,77.2,C
5,Maddie Johnson,18,Female,65,92,41,59,67,324,106,64.8,D
6,Amiyah Taylor,20,Female,86,99,46,83,47,361,132,72.2,C
7,Tre Anderson,20,Female,86,74,53,56,75,344,139,68.8,D
8,Ray Smith,24,Female,89,79,43,41,45,297,132,59.4,F
9,Makayla Taylor,19,Male,93,81,43,93,68,378,136,75.6,C

In [16]:
df_new['Percentage_bonus']=df_new['Percentage'].apply(lambda x: x+5)
df_new

,Name,Age,Gender,Physics,Math,CS,English,History,Total,Sci_total,Percentage,Grade,Percentage_bonus
0,Tre Taylor,19,Male,67,99,55,54,86,361,122,72.2,C,77.2
1,Kenny Brown,23,Female,90,83,94,91,96,454,184,90.8,A,95.8
2,Ray Anderson,22,Female,42,76,90,46,60,314,132,62.8,D,67.8
3,Makayla Johnson,21,Female,48,78,57,43,64,290,105,58.0,F,63.0
4,Tre Taylor,18,Female,99,53,89,97,48,386,188,77.2,C,82.2
5,Maddie Johnson,18,Female,65,92,41,59,67,324,106,64.8,D,69.8
6,Amiyah Taylor,20,Female,86,99,46,83,47,361,132,72.2,C,77.2
7,Tre Anderson,20,Female,86,74,53,56,75,344,139,68.8,D,73.8
8,Ray Smith,24,Female,89,79,43,41,45,297,132,59.4,F,64.4
9,Makayla Taylor,19,Male,93,81,43,93,68,378,136,75.6,C,80.6

In [17]:
print('Data Frame before dropping bonus column:\n', df_new)
df_new.drop(columns=['Percentage_bonus'], inplace=True)
print('Data Frame after dropping bonus column:\n', df_new)

Data Frame before dropping bonus column:
               Name  Age  Gender  Physics  Math  CS  English  History  Total  \
0       Tre Taylor   19    Male       67    99  55       54       86    361
1      Kenny Brown   23  Female       90    83  94       91       96    454
2     Ray Anderson   22  Female       42    76  90       46       60    314
3  Makayla Johnson   21  Female       48    78  57       43       64    290
4       Tre Taylor   18  Female       99    53  89       97       48    386
5   Maddie Johnson   18  Female       65    92  41       59       67    324
6    Amiyah Taylor   20  Female       86    99  46       83       47    361
7     Tre Anderson   20  Female       86    74  53       56       75    344
8        Ray Smith   24  Female       89    79  43       41       45    297
9   Makayla Taylor   19    Male       93    81  43       93       68    378

   Sci_total  Percentage Grade  Percentage_bonus
0        122        72.2     C              77.2
1        184        90.8     A              95.8
2        132        62.8     D              67.8
3        105        58.0     F              63.0
4        188        77.2     C              82.2
5        106        64.8     D              69.8
6        132        72.2     C              77.2
7        139        68.8     D              73.8
8        132        59.4     F              64.4
9        136        75.6     C              80.6
Data Frame after dropping bonus column:
               Name  Age  Gender  Physics  Math  CS  English  History  Total  \
0       Tre Taylor   19    Male       67    99  55       54       86    361
1      Kenny Brown   23  Female       90    83  94       91       96    454
2     Ray Anderson   22  Female       42    76  90       46       60    314
3  Makayla Johnson   21  Female       48    78  57       43       64    290
4       Tre Taylor   18  Female       99    53  89       97       48    386
5   Maddie Johnson   18  Female       65    92  41       59       67    324
6    Amiyah Taylor   20  Female       86    99  46       83       47    361
7     Tre Anderson   20  Female       86    74  53       56       75    344
8        Ray Smith   24  Female       89    79  43       41       45    297
9   Makayla Taylor   19    Male       93    81  43       93       68    378

   Sci_total  Percentage Grade
0        122        72.2     C
1        184        90.8     A
2        132        62.8     D
3        105        58.0     F
4        188        77.2     C
5        106        64.8     D
6        132        72.2     C
7        139        68.8     D
8        132        59.4     F
9        136        75.6     C

In [18]:
df_new

,Name,Age,Gender,Physics,Math,CS,English,History,Total,Sci_total,Percentage,Grade
0,Tre Taylor,19,Male,67,99,55,54,86,361,122,72.2,C
1,Kenny Brown,23,Female,90,83,94,91,96,454,184,90.8,A
2,Ray Anderson,22,Female,42,76,90,46,60,314,132,62.8,D
3,Makayla Johnson,21,Female,48,78,57,43,64,290,105,58.0,F
4,Tre Taylor,18,Female,99,53,89,97,48,386,188,77.2,C
5,Maddie Johnson,18,Female,65,92,41,59,67,324,106,64.8,D
6,Amiyah Taylor,20,Female,86,99,46,83,47,361,132,72.2,C
7,Tre Anderson,20,Female,86,74,53,56,75,344,139,68.8,D
8,Ray Smith,24,Female,89,79,43,41,45,297,132,59.4,F
9,Makayla Taylor,19,Male,93,81,43,93,68,378,136,75.6,C

In [19]:
df_filtered=df_new[df_new['Physics']>70]
df_filtered

,Name,Age,Gender,Physics,Math,CS,English,History,Total,Sci_total,Percentage,Grade
1,Kenny Brown,23,Female,90,83,94,91,96,454,184,90.8,A
4,Tre Taylor,18,Female,99,53,89,97,48,386,188,77.2,C
6,Amiyah Taylor,20,Female,86,99,46,83,47,361,132,72.2,C
7,Tre Anderson,20,Female,86,74,53,56,75,344,139,68.8,D
8,Ray Smith,24,Female,89,79,43,41,45,297,132,59.4,F
9,Makayla Taylor,19,Male,93,81,43,93,68,378,136,75.6,C

In [20]:
df_A=df_new[df_new['Percentage']>=90]
df_A

,Name,Age,Gender,Physics,Math,CS,English,History,Total,Sci_total,Percentage,Grade
1,Kenny Brown,23,Female,90,83,94,91,96,454,184,90.8,A

In [21]:
filtered_df=df_new[(df_new['Physics']>60)&(df_new['Math']>60)]
filtered_df

,Name,Age,Gender,Physics,Math,CS,English,History,Total,Sci_total,Percentage,Grade
0,Tre Taylor,19,Male,67,99,55,54,86,361,122,72.2,C
1,Kenny Brown,23,Female,90,83,94,91,96,454,184,90.8,A
5,Maddie Johnson,18,Female,65,92,41,59,67,324,106,64.8,D
6,Amiyah Taylor,20,Female,86,99,46,83,47,361,132,72.2,C
7,Tre Anderson,20,Female,86,74,53,56,75,344,139,68.8,D
8,Ray Smith,24,Female,89,79,43,41,45,297,132,59.4,F
9,Makayla Taylor,19,Male,93,81,43,93,68,378,136,75.6,C

In [22]:
df_new.rename(columns={'Name':'Students_Name'},inplace=True)
df_new

,Students_Name,Age,Gender,Physics,Math,CS,English,History,Total,Sci_total,Percentage,Grade
0,Tre Taylor,19,Male,67,99,55,54,86,361,122,72.2,C
1,Kenny Brown,23,Female,90,83,94,91,96,454,184,90.8,A
2,Ray Anderson,22,Female,42,76,90,46,60,314,132,62.8,D
3,Makayla Johnson,21,Female,48,78,57,43,64,290,105,58.0,F
4,Tre Taylor,18,Female,99,53,89,97,48,386,188,77.2,C
5,Maddie Johnson,18,Female,65,92,41,59,67,324,106,64.8,D
6,Amiyah Taylor,20,Female,86,99,46,83,47,361,132,72.2,C
7,Tre Anderson,20,Female,86,74,53,56,75,344,139,68.8,D
8,Ray Smith,24,Female,89,79,43,41,45,297,132,59.4,F
9,Makayla Taylor,19,Male,93,81,43,93,68,378,136,75.6,C

In [23]:
df_index=df_new.set_index('Students_Name')
df_index

,Age,Gender,Physics,Math,CS,English,History,Total,Sci_total,Percentage,Grade
Students_Name,,,,,,,,,,,
Tre Taylor,19,Male,67,99,55,54,86,361,122,72.2,C
Kenny Brown,23,Female,90,83,94,91,96,454,184,90.8,A
Ray Anderson,22,Female,42,76,90,46,60,314,132,62.8,D
Makayla Johnson,21,Female,48,78,57,43,64,290,105,58.0,F
Tre Taylor,18,Female,99,53,89,97,48,386,188,77.2,C
Maddie Johnson,18,Female,65,92,41,59,67,324,106,64.8,D
Amiyah Taylor,20,Female,86,99,46,83,47,361,132,72.2,C
Tre Anderson,20,Female,86,74,53,56,75,344,139,68.8,D
Ray Smith,24,Female,89,79,43,41,45,297,132,59.4,F
Makayla Taylor,19,Male,93,81,43,93,68,378,136,75.6,C

In [24]:
df_new.to_csv('student_raw_data_new.csv', index=False)

In [25]:
pd.read_csv('student_raw_data_new.csv')

,Students_Name,Age,Gender,Physics,Math,CS,English,History,Total,Sci_total,Percentage,Grade
0,Tre Taylor,19,Male,67,99,55,54,86,361,122,72.2,C
1,Kenny Brown,23,Female,90,83,94,91,96,454,184,90.8,A
2,Ray Anderson,22,Female,42,76,90,46,60,314,132,62.8,D
3,Makayla Johnson,21,Female,48,78,57,43,64,290,105,58.0,F
4,Tre Taylor,18,Female,99,53,89,97,48,386,188,77.2,C
5,Maddie Johnson,18,Female,65,92,41,59,67,324,106,64.8,D
6,Amiyah Taylor,20,Female,86,99,46,83,47,361,132,72.2,C
7,Tre Anderson,20,Female,86,74,53,56,75,344,139,68.8,D
8,Ray Smith,24,Female,89,79,43,41,45,297,132,59.4,F
9,Makayla Taylor,19,Male,93,81,43,93,68,378,136,75.6,C