In [1]:
import numpy as np
import pandas as pd

In [2]:
n=200
np.random.seed(42)
user=['Alexis','Danya','James','Kendra','Elliot','Amiyah','Dante','Rose','Ben','Elaine']
device_model=['Iphone13','Samsung','Iphone15','Google_pixel','Iphone16']
data={
    'User':np.random.choice(user,size=n),
    'Device_Model':np.random.choice(device_model,size=n),
    'Screentime(hrs)':np.random.randint(1,12,size=n)
}
ages=np.random.normal(loc=30, scale=8, size=n).round(1)
gender=np.random.choice(['Male','Female'],size=n)
mobile_data=pd.DataFrame(data)
mobile_data

       User  Device_Model  Screentime(hrs)
0     Dante      Iphone15                5
1    Kendra      Iphone13                6
2      Rose      Iphone13                9
3    Elliot  Google_pixel                5
4     Dante      Iphone15                1
..      ...           ...              ...
195    Rose      Iphone16                3
196  Elliot      Iphone15                4
197  Kendra  Google_pixel                9
198   Danya       Samsung                2
199  Amiyah      Iphone15                9

[200 rows x 3 columns]

In [3]:
mobile_data.insert(1,'Gender',gender)

In [4]:
mobile_data.insert(2,'Age',ages)

In [5]:
mobile_data

       User  Gender   Age  Device_Model  Screentime(hrs)
0     Dante    Male  24.4      Iphone15                5
1    Kendra    Male  22.3      Iphone13                6
2      Rose  Female  41.5      Iphone13                9
3    Elliot    Male  24.4  Google_pixel                5
4     Dante  Female  28.9      Iphone15                1
..      ...     ...   ...           ...              ...
195    Rose    Male  33.8      Iphone16                3
196  Elliot  Female  25.4      Iphone15                4
197  Kendra  Female  24.6  Google_pixel                9
198   Danya    Male  35.9       Samsung                2
199  Amiyah    Male  31.9      Iphone15                9

[200 rows x 5 columns]

In [6]:
mobile_data.to_csv('mobile_data_raw.csv',index=False)

In [7]:
df=pd.read_csv('mobile_data_raw.csv')
df

       User  Gender   Age  Device_Model  Screentime(hrs)
0     Dante    Male  24.4      Iphone15                5
1    Kendra    Male  22.3      Iphone13                6
2      Rose  Female  41.5      Iphone13                9
3    Elliot    Male  24.4  Google_pixel                5
4     Dante  Female  28.9      Iphone15                1
..      ...     ...   ...           ...              ...
195    Rose    Male  33.8      Iphone16                3
196  Elliot  Female  25.4      Iphone15                4
197  Kendra  Female  24.6  Google_pixel                9
198   Danya    Male  35.9       Samsung                2
199  Amiyah    Male  31.9      Iphone15                9

[200 rows x 5 columns]

In [8]:
df.head(3)

     User  Gender   Age Device_Model  Screentime(hrs)
0   Dante    Male  24.4     Iphone15                5
1  Kendra    Male  22.3     Iphone13                6
2    Rose  Female  41.5     Iphone13                9

In [9]:
df.tail(3)

       User  Gender   Age  Device_Model  Screentime(hrs)
197  Kendra  Female  24.6  Google_pixel                9
198   Danya    Male  35.9       Samsung                2
199  Amiyah    Male  31.9      Iphone15                9

In [10]:
df.size

1000

In [11]:
df.columns #

Index(['User', 'Gender', 'Age', 'Device_Model', 'Screentime(hrs)'], dtype='object')

In [12]:
df.info

<bound method DataFrame.info of        User  Gender   Age  Device_Model  Screentime(hrs)
0     Dante    Male  24.4      Iphone15                5
1    Kendra    Male  22.3      Iphone13                6
2      Rose  Female  41.5      Iphone13                9
3    Elliot    Male  24.4  Google_pixel                5
4     Dante  Female  28.9      Iphone15                1
..      ...     ...   ...           ...              ...
195    Rose    Male  33.8      Iphone16                3
196  Elliot  Female  25.4      Iphone15                4
197  Kendra  Female  24.6  Google_pixel                9
198   Danya    Male  35.9       Samsung                2
199  Amiyah    Male  31.9      Iphone15                9

[200 rows x 5 columns]>

In [18]:
print(f'the shape of the data frame:\n') #200 rows and 5 columns
df.shape

the shape of the data frame:

(200, 5)

In [17]:
print(f' the data types of the data frame:\n')
df.dtypes

 the data types of the data frame:

User                object
Gender              object
Age                float64
Device_Model        object
Screentime(hrs)      int64
dtype: object

In [19]:
df.select_dtypes(include=['number']) #these are the numerical columns

      Age  Screentime(hrs)
0    24.4                5
1    22.3                6
2    41.5                9
3    24.4                5
4    28.9                1
..    ...              ...
195  33.8                3
196  25.4                4
197  24.6                9
198  35.9                2
199  31.9                9

[200 rows x 2 columns]

In [20]:
df.select_dtypes(include=['object']) #these are the categorial columns

       User  Gender  Device_Model
0     Dante    Male      Iphone15
1    Kendra    Male      Iphone13
2      Rose  Female      Iphone13
3    Elliot    Male  Google_pixel
4     Dante  Female      Iphone15
..      ...     ...           ...
195    Rose    Male      Iphone16
196  Elliot  Female      Iphone15
197  Kendra  Female  Google_pixel
198   Danya    Male       Samsung
199  Amiyah    Male      Iphone15

[200 rows x 3 columns]

In [30]:
df.describe()

              Age  Screentime(hrs)
count  200.000000       200.000000
mean    30.136000         5.865000
std      8.063467         3.149025
min      9.100000         1.000000
25%     24.600000         3.000000
50%     30.450000         5.000000
75%     35.625000         9.000000
max     47.400000        11.000000

In [31]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
195    False
196    False
197    False
198    False
199    False
Length: 200, dtype: bool

In [32]:
df.isnull()

      User  Gender    Age  Device_Model  Screentime(hrs)
0    False   False  False         False            False
1    False   False  False         False            False
2    False   False  False         False            False
3    False   False  False         False            False
4    False   False  False         False            False
..     ...     ...    ...           ...              ...
195  False   False  False         False            False
196  False   False  False         False            False
197  False   False  False         False            False
198  False   False  False         False            False
199  False   False  False         False            False

[200 rows x 5 columns]

In [35]:
df['User'].unique()

array(['Dante', 'Kendra', 'Rose', 'Elliot', 'Elaine', 'James', 'Amiyah',
       'Danya', 'Alexis', 'Ben'], dtype=object)