# Indexing

In [1]:
import numpy as np
import pandas as pd

In [2]:
df_new=pd.read_csv('student_raw_data_new.csv')
df_new

,Students_Name,Age,Gender,Physics,Math,CS,English,History,Total,Sci_total,Percentage,Grade
0,Tre Taylor,19,Male,67,99,55,54,86,361,122,72.2,C
1,Kenny Brown,23,Female,90,83,94,91,96,454,184,90.8,A
2,Ray Anderson,22,Female,42,76,90,46,60,314,132,62.8,D
3,Makayla Johnson,21,Female,48,78,57,43,64,290,105,58.0,F
4,Tre Taylor,18,Female,99,53,89,97,48,386,188,77.2,C
5,Maddie Johnson,18,Female,65,92,41,59,67,324,106,64.8,D
6,Amiyah Taylor,20,Female,86,99,46,83,47,361,132,72.2,C
7,Tre Anderson,20,Female,86,74,53,56,75,344,139,68.8,D
8,Ray Smith,24,Female,89,79,43,41,45,297,132,59.4,F
9,Makayla Taylor,19,Male,93,81,43,93,68,378,136,75.6,C

* loc (label-based)
* iloc (number-based)

In [3]:
df_new.iloc[0]

Students_Name    Tre Taylor
Age                      19
Gender                 Male
Physics                  67
Math                     99
CS                       55
English                  54
History                  86
Total                   361
Sci_total               122
Percentage             72.2
Grade                     C
Name: 0, dtype: object

In [4]:
df_new.loc[0]

Students_Name    Tre Taylor
Age                      19
Gender                 Male
Physics                  67
Math                     99
CS                       55
English                  54
History                  86
Total                   361
Sci_total               122
Percentage             72.2
Grade                     C
Name: 0, dtype: object

In [6]:
print(df_new.iloc[0,4])

99

In [7]:
print(df_new.loc[0,'Math'])

99

In [9]:
df_new.iloc[1:3]

,Students_Name,Age,Gender,Physics,Math,CS,English,History,Total,Sci_total,Percentage,Grade
1,Kenny Brown,23,Female,90,83,94,91,96,454,184,90.8,A
2,Ray Anderson,22,Female,42,76,90,46,60,314,132,62.8,D

In [10]:
df_new.loc[1:3]

,Students_Name,Age,Gender,Physics,Math,CS,English,History,Total,Sci_total,Percentage,Grade
1,Kenny Brown,23,Female,90,83,94,91,96,454,184,90.8,A
2,Ray Anderson,22,Female,42,76,90,46,60,314,132,62.8,D
3,Makayla Johnson,21,Female,48,78,57,43,64,290,105,58.0,F

In [11]:
df_index=df_new.set_index('Students_Name')
df_index

,Age,Gender,Physics,Math,CS,English,History,Total,Sci_total,Percentage,Grade
Students_Name,,,,,,,,,,,
Tre Taylor,19,Male,67,99,55,54,86,361,122,72.2,C
Kenny Brown,23,Female,90,83,94,91,96,454,184,90.8,A
Ray Anderson,22,Female,42,76,90,46,60,314,132,62.8,D
Makayla Johnson,21,Female,48,78,57,43,64,290,105,58.0,F
Tre Taylor,18,Female,99,53,89,97,48,386,188,77.2,C
Maddie Johnson,18,Female,65,92,41,59,67,324,106,64.8,D
Amiyah Taylor,20,Female,86,99,46,83,47,361,132,72.2,C
Tre Anderson,20,Female,86,74,53,56,75,344,139,68.8,D
Ray Smith,24,Female,89,79,43,41,45,297,132,59.4,F
Makayla Taylor,19,Male,93,81,43,93,68,378,136,75.6,C

In [12]:
df_index.iloc[0]

Age             19
Gender        Male
Physics         67
Math            99
CS              55
English         54
History         86
Total          361
Sci_total      122
Percentage    72.2
Grade            C
Name: Tre Taylor, dtype: object

In [13]:
df_index.loc['Tre Taylor']

,Age,Gender,Physics,Math,CS,English,History,Total,Sci_total,Percentage,Grade
Students_Name,,,,,,,,,,,
Tre Taylor,19,Male,67,99,55,54,86,361,122,72.2,C
Tre Taylor,18,Female,99,53,89,97,48,386,188,77.2,C

In [16]:
df_sorted=df_new.sort_values(by='Physics',ascending=False)
df_sorted

,Students_Name,Age,Gender,Physics,Math,CS,English,History,Total,Sci_total,Percentage,Grade
4,Tre Taylor,18,Female,99,53,89,97,48,386,188,77.2,C
9,Makayla Taylor,19,Male,93,81,43,93,68,378,136,75.6,C
1,Kenny Brown,23,Female,90,83,94,91,96,454,184,90.8,A
8,Ray Smith,24,Female,89,79,43,41,45,297,132,59.4,F
6,Amiyah Taylor,20,Female,86,99,46,83,47,361,132,72.2,C
7,Tre Anderson,20,Female,86,74,53,56,75,344,139,68.8,D
0,Tre Taylor,19,Male,67,99,55,54,86,361,122,72.2,C
5,Maddie Johnson,18,Female,65,92,41,59,67,324,106,64.8,D
3,Makayla Johnson,21,Female,48,78,57,43,64,290,105,58.0,F
2,Ray Anderson,22,Female,42,76,90,46,60,314,132,62.8,D

## Group by

In [18]:
df_new.groupby('Gender')[['Physics', 'Math', 'CS']].mean()

        Physics   Math      CS
Gender
Female   75.625  79.25  64.125
Male     80.000  90.00  49.000

In [19]:
df_new.groupby('Gender')[['Physics', 'Math', 'CS']].agg(['mean', 'max', 'count'])

       Physics             Math                CS
          mean max count   mean max count    mean max count
Gender
Female  75.625  99     8  79.25  99     8  64.125  94     8
Male    80.000  93     2  90.00  99     2  49.000  55     2