## Dataset Information

* This dataset is called Vehicle Fuel Economy Estimates.

* This dataset was obtained on Kaggle: [Vehicle Fuel Economy Estimates](https://www.kaggle.com/datasets/epa/fuel-economy)

* The information in this dataset contains the fuel economy estimates of different vehicles. Fuel economy is the measure of how far a vehicle can travel on a set amount of fuel. The EPA's fuel economy estimates allow drivers to understand how their car will perform under average conditions and help them compare different cars/models to each other. Our group will be focusing on which car brand produced the most fuel efficient vehicles or trends in fuel economy efficiency over time

In [3]:
#importing the libraries
import numpy as np
import pandas as pd

In [4]:
#load the dataset
df=pd.read_csv('database.csv', low_memory=False)
df

,Vehicle ID,Year,Make,Model,Class,Drive,Transmission,Transmission Descriptor,Engine Index,Engine Descriptor,...,Hours to Charge (AC 240V),Composite City MPG,Composite Highway MPG,Composite Combined MPG,Range (FT1),City Range (FT1),Highway Range (FT1),Range (FT2),City Range (FT2),Highway Range (FT2)
0,26587,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,NaN,Manual 5-Speed,NaN,9001,(FFS),...,0.0,0,0,0,0,0.0,0.0,NaN,0.00,0.0
1,27705,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,NaN,Manual 5-Speed,NaN,9005,(FFS) CA model,...,0.0,0,0,0,0,0.0,0.0,NaN,0.00,0.0
2,26561,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,NaN,Manual 5-Speed,NaN,9002,(FFS),...,0.0,0,0,0,0,0.0,0.0,NaN,0.00,0.0
3,27681,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,NaN,Manual 5-Speed,NaN,9006,(FFS) CA model,...,0.0,0,0,0,0,0.0,0.0,NaN,0.00,0.0
4,27550,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,2-Wheel Drive,Automatic 3-Speed,NaN,1830,(FFS),...,0.0,0,0,0,0,0.0,0.0,NaN,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38108,37564,2017,Volvo,XC60 FWD,Small Sport Utility Vehicle 2WD,Front-Wheel Drive,Automatic (S8),NaN,90,SIDI,...,0.0,0,0,0,0,0.0,0.0,NaN,0.00,0.0
38109,37547,2017,Volvo,XC90 AWD,Standard Sport Utility Vehicle 4WD,All-Wheel Drive,Automatic (S8),NaN,52,SIDI,...,0.0,0,0,0,0,0.0,0.0,NaN,0.00,0.0
38110,37548,2017,Volvo,XC90 AWD,Standard Sport Utility Vehicle 4WD,All-Wheel Drive,Automatic (S8),NaN,53,SIDI,...,0.0,0,0,0,0,0.0,0.0,NaN,0.00,0.0
38111,37703,2017,Volvo,XC90 AWD PHEV,Standard Sport Utility Vehicle 4WD,All-Wheel Drive,Automatic (S8),NaN,54,SIDI; PHEV,...,0.0,29,32,30,0,0.0,0.0,14,13.84,13.3
38112,37687,2017,Volvo,XC90 FWD,Standard Sport Utility Vehicle 2WD,Front-Wheel Drive,Automatic (S8),NaN,50,SIDI,...,0.0,0,0,0,0,0.0,0.0,NaN,0.00,0.0

In [5]:
#the first five rows of the dataset
print('The first five rows of the dataset:\n')
df.head()

The first five rows of the dataset:

,Vehicle ID,Year,Make,Model,Class,Drive,Transmission,Transmission Descriptor,Engine Index,Engine Descriptor,...,Hours to Charge (AC 240V),Composite City MPG,Composite Highway MPG,Composite Combined MPG,Range (FT1),City Range (FT1),Highway Range (FT1),Range (FT2),City Range (FT2),Highway Range (FT2)
0,26587,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,NaN,Manual 5-Speed,NaN,9001,(FFS),...,0.0,0,0,0,0,0.0,0.0,NaN,0.0,0.0
1,27705,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,NaN,Manual 5-Speed,NaN,9005,(FFS) CA model,...,0.0,0,0,0,0,0.0,0.0,NaN,0.0,0.0
2,26561,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,NaN,Manual 5-Speed,NaN,9002,(FFS),...,0.0,0,0,0,0,0.0,0.0,NaN,0.0,0.0
3,27681,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,NaN,Manual 5-Speed,NaN,9006,(FFS) CA model,...,0.0,0,0,0,0,0.0,0.0,NaN,0.0,0.0
4,27550,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,2-Wheel Drive,Automatic 3-Speed,NaN,1830,(FFS),...,0.0,0,0,0,0,0.0,0.0,NaN,0.0,0.0

In [6]:
#the last five rows of the dataset
print('The last five rows of the dataset:\n')
df.tail()

The last five rows of the dataset:

,Vehicle ID,Year,Make,Model,Class,Drive,Transmission,Transmission Descriptor,Engine Index,Engine Descriptor,...,Hours to Charge (AC 240V),Composite City MPG,Composite Highway MPG,Composite Combined MPG,Range (FT1),City Range (FT1),Highway Range (FT1),Range (FT2),City Range (FT2),Highway Range (FT2)
38108,37564,2017,Volvo,XC60 FWD,Small Sport Utility Vehicle 2WD,Front-Wheel Drive,Automatic (S8),NaN,90,SIDI,...,0.0,0,0,0,0,0.0,0.0,NaN,0.00,0.0
38109,37547,2017,Volvo,XC90 AWD,Standard Sport Utility Vehicle 4WD,All-Wheel Drive,Automatic (S8),NaN,52,SIDI,...,0.0,0,0,0,0,0.0,0.0,NaN,0.00,0.0
38110,37548,2017,Volvo,XC90 AWD,Standard Sport Utility Vehicle 4WD,All-Wheel Drive,Automatic (S8),NaN,53,SIDI,...,0.0,0,0,0,0,0.0,0.0,NaN,0.00,0.0
38111,37703,2017,Volvo,XC90 AWD PHEV,Standard Sport Utility Vehicle 4WD,All-Wheel Drive,Automatic (S8),NaN,54,SIDI; PHEV,...,0.0,29,32,30,0,0.0,0.0,14,13.84,13.3
38112,37687,2017,Volvo,XC90 FWD,Standard Sport Utility Vehicle 2WD,Front-Wheel Drive,Automatic (S8),NaN,50,SIDI,...,0.0,0,0,0,0,0.0,0.0,NaN,0.00,0.0

In [7]:
#dimensions of the dataset/how many rows & columns
df.shape

(38113, 81)

In [8]:
#column names
df.columns.tolist()

['Vehicle ID',
 'Year',
 'Make',
 'Model',
 'Class',
 'Drive',
 'Transmission',
 'Transmission Descriptor',
 'Engine Index',
 'Engine Descriptor',
 'Engine Cylinders',
 'Engine Displacement',
 'Turbocharger',
 'Supercharger',
 'Fuel Type',
 'Fuel Type 1',
 'Fuel Type 2',
 'City MPG (FT1)',
 'Unrounded City MPG (FT1)',
 'City MPG (FT2)',
 'Unrounded City MPG (FT2)',
 'City Gasoline Consumption (CD)',
 'City Electricity Consumption',
 'City Utility Factor',
 'Highway MPG (FT1)',
 'Unrounded Highway MPG (FT1)',
 'Highway MPG (FT2)',
 'Unrounded Highway MPG (FT2)',
 'Highway Gasoline Consumption (CD)',
 'Highway Electricity Consumption',
 'Highway Utility Factor',
 'Unadjusted City MPG (FT1)',
 'Unadjusted Highway MPG (FT1)',
 'Unadjusted City MPG (FT2)',
 'Unadjusted Highway MPG (FT2)',
 'Combined MPG (FT1)',
 'Unrounded Combined MPG (FT1)',
 'Combined MPG (FT2)',
 'Unrounded Combined MPG (FT2)',
 'Combined Electricity Consumption',
 'Combined Gasoline Consumption (CD)',
 'Combined Utility Factor',
 'Annual Fuel Cost (FT1)',
 'Annual Fuel Cost (FT2)',
 'Gas Guzzler Tax',
 'Save or Spend (5 Year)',
 'Annual Consumption in Barrels (FT1)',
 'Annual Consumption in Barrels (FT2)',
 'Tailpipe CO2 (FT1)',
 'Tailpipe CO2 in Grams/Mile (FT1)',
 'Tailpipe CO2 (FT2)',
 'Tailpipe CO2 in Grams/Mile (FT2)',
 'Fuel Economy Score',
 'GHG Score',
 'GHG Score (Alt Fuel)',
 'My MPG Data',
 '2D Passenger Volume',
 '2D Luggage Volume',
 '4D Passenger Volume',
 '4D Luggage Volume',
 'Hatchback Passenger Volume',
 'Hatchback Luggage Volume',
 'Start Stop Technology',
 'Alternative Fuel/Technology',
 'Electric Motor',
 'Manufacturer Code',
 'Gasoline/Electricity Blended (CD)',
 'Vehicle Charger',
 'Alternate Charger',
 'Hours to Charge (120V)',
 'Hours to Charge (240V)',
 'Hours to Charge (AC 240V)',
 'Composite City MPG',
 'Composite Highway MPG',
 'Composite Combined MPG',
 'Range (FT1)',
 'City Range (FT1)',
 'Highway Range (FT1)',
 'Range (FT2)',
 'City Range (FT2)',
 'Highway Range (FT2)']

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38113 entries, 0 to 38112
Data columns (total 81 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Vehicle ID                           38113 non-null  int64
 1   Year                                 38113 non-null  int64
 2   Make                                 38113 non-null  object
 3   Model                                38113 non-null  object
 4   Class                                38113 non-null  object
 5   Drive                                36924 non-null  object
 6   Transmission                         38102 non-null  object
 7   Transmission Descriptor              15045 non-null  object
 8   Engine Index                         38113 non-null  int64
 9   Engine Descriptor                    22693 non-null  object
 10  Engine Cylinders                     37977 non-null  float64
 11  Engine Displacement                  37979 non-null  float64
 12  Turbocharger                         5239 non-null   object
 13  Supercharger                         693 non-null    object
 14  Fuel Type                            38113 non-null  object
 15  Fuel Type 1                          38113 non-null  object
 16  Fuel Type 2                          1438 non-null   object
 17  City MPG (FT1)                       38113 non-null  int64
 18  Unrounded City MPG (FT1)             38113 non-null  float64
 19  City MPG (FT2)                       38113 non-null  int64
 20  Unrounded City MPG (FT2)             38113 non-null  float64
 21  City Gasoline Consumption (CD)       38113 non-null  float64
 22  City Electricity Consumption         38113 non-null  float64
 23  City Utility Factor                  38113 non-null  float64
 24  Highway MPG (FT1)                    38113 non-null  int64
 25  Unrounded Highway MPG (FT1)          38113 non-null  float64
 26  Highway MPG (FT2)                    38113 non-null  int64
 27  Unrounded Highway MPG (FT2)          38113 non-null  float64
 28  Highway Gasoline Consumption (CD)    38113 non-null  float64
 29  Highway Electricity Consumption      38113 non-null  float64
 30  Highway Utility Factor               38113 non-null  float64
 31  Unadjusted City MPG (FT1)            38113 non-null  float64
 32  Unadjusted Highway MPG (FT1)         38113 non-null  float64
 33  Unadjusted City MPG (FT2)            38113 non-null  float64
 34  Unadjusted Highway MPG (FT2)         38113 non-null  float64
 35  Combined MPG (FT1)                   38113 non-null  int64
 36  Unrounded Combined MPG (FT1)         38113 non-null  float64
 37  Combined MPG (FT2)                   38113 non-null  int64
 38  Unrounded Combined MPG (FT2)         38113 non-null  float64
 39  Combined Electricity Consumption     38113 non-null  float64
 40  Combined Gasoline Consumption (CD)   38113 non-null  float64
 41  Combined Utility Factor              38113 non-null  float64
 42  Annual Fuel Cost (FT1)               38113 non-null  int64
 43  Annual Fuel Cost (FT2)               38113 non-null  int64
 44  Gas Guzzler Tax                      2296 non-null   object
 45  Save or Spend (5 Year)               38113 non-null  int64
 46  Annual Consumption in Barrels (FT1)  38113 non-null  float64
 47  Annual Consumption in Barrels (FT2)  38113 non-null  float64
 48  Tailpipe CO2 (FT1)                   38113 non-null  int64
 49  Tailpipe CO2 in Grams/Mile (FT1)     38113 non-null  float64
 50  Tailpipe CO2 (FT2)                   38113 non-null  int64
 51  Tailpipe CO2 in Grams/Mile (FT2)     38113 non-null  float64
 52  Fuel Economy Score                   38113 non-null  int64
 53  GHG Score                            38113 non-null  int64
 54  GHG Score (Alt Fuel)                 38113 non-null  int64
 55  My MPG Data                          38113 non-null  object
 56  2D Passenger Volume                  38113 non-null  int64
 57  2D Luggage Volume                    38113 non-null  int64
 58  4D Passenger Volume                  38113 non-null  int64
 59  4D Luggage Volume                    38113 non-null  int64
 60  Hatchback Passenger Volume           38113 non-null  int64
 61  Hatchback Luggage Volume             38113 non-null  int64
 62  Start Stop Technology                6443 non-null   object
 63  Alternative Fuel/Technology          3047 non-null   object
 64  Electric Motor                       604 non-null    object
 65  Manufacturer Code                    7319 non-null   object
 66  Gasoline/Electricity Blended (CD)    38113 non-null  bool
 67  Vehicle Charger                      48 non-null     object
 68  Alternate Charger                    46 non-null     object
 69  Hours to Charge (120V)               38113 non-null  int64
 70  Hours to Charge (240V)               38113 non-null  float64
 71  Hours to Charge (AC 240V)            38113 non-null  float64
 72  Composite City MPG                   38113 non-null  int64
 73  Composite Highway MPG                38113 non-null  int64
 74  Composite Combined MPG               38113 non-null  int64
 75  Range (FT1)                          38113 non-null  int64
 76  City Range (FT1)                     38113 non-null  float64
 77  Highway Range (FT1)                  38113 non-null  float64
 78  Range (FT2)                          1433 non-null   object
 79  City Range (FT2)                     38113 non-null  float64
 80  Highway Range (FT2)                  38113 non-null  float64
dtypes: bool(1), float64(31), int64(28), object(21)
memory usage: 23.3+ MB

In [10]:
df.select_dtypes(include='number')

,Vehicle ID,Year,Engine Index,Engine Cylinders,Engine Displacement,City MPG (FT1),Unrounded City MPG (FT1),City MPG (FT2),Unrounded City MPG (FT2),City Gasoline Consumption (CD),...,Hours to Charge (240V),Hours to Charge (AC 240V),Composite City MPG,Composite Highway MPG,Composite Combined MPG,Range (FT1),City Range (FT1),Highway Range (FT1),City Range (FT2),Highway Range (FT2)
0,26587,1984,9001,6.0,2.5,17,0.0000,0,0.0000,0.0000,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0
1,27705,1984,9005,6.0,2.5,17,0.0000,0,0.0000,0.0000,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0
2,26561,1984,9002,4.0,2.0,18,0.0000,0,0.0000,0.0000,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0
3,27681,1984,9006,4.0,2.0,18,0.0000,0,0.0000,0.0000,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0
4,27550,1984,1830,4.0,2.5,18,0.0000,0,0.0000,0.0000,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38108,37564,2017,90,4.0,2.0,23,22.6786,0,0.0000,0.0000,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0
38109,37547,2017,52,4.0,2.0,20,20.4122,0,0.0000,0.0000,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0
38110,37548,2017,53,4.0,2.0,22,21.7000,0,0.0000,0.0000,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0
38111,37703,2017,54,4.0,2.0,24,23.7174,54,58.5962,0.0541,...,3.0,0.0,29,32,30,0,0.0,0.0,13.84,13.3
38112,37687,2017,50,4.0,2.0,22,22.1000,0,0.0000,0.0000,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0

In [11]:
df.select_dtypes(include='object')

,Make,Model,Class,Drive,Transmission,Transmission Descriptor,Engine Descriptor,Turbocharger,Supercharger,Fuel Type,...,Fuel Type 2,Gas Guzzler Tax,My MPG Data,Start Stop Technology,Alternative Fuel/Technology,Electric Motor,Manufacturer Code,Vehicle Charger,Alternate Charger,Range (FT2)
0,Alfa Romeo,GT V6 2.5,Minicompact Cars,NaN,Manual 5-Speed,NaN,(FFS),NaN,NaN,Regular,...,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Alfa Romeo,GT V6 2.5,Minicompact Cars,NaN,Manual 5-Speed,NaN,(FFS) CA model,NaN,NaN,Regular,...,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Alfa Romeo,Spider Veloce 2000,Two Seaters,NaN,Manual 5-Speed,NaN,(FFS),NaN,NaN,Regular,...,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Alfa Romeo,Spider Veloce 2000,Two Seaters,NaN,Manual 5-Speed,NaN,(FFS) CA model,NaN,NaN,Regular,...,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,2-Wheel Drive,Automatic 3-Speed,NaN,(FFS),NaN,NaN,Regular,...,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38108,Volvo,XC60 FWD,Small Sport Utility Vehicle 2WD,Front-Wheel Drive,Automatic (S8),NaN,SIDI,T,NaN,Regular,...,NaN,NaN,N,Y,NaN,NaN,VVX,NaN,NaN,NaN
38109,Volvo,XC90 AWD,Standard Sport Utility Vehicle 4WD,All-Wheel Drive,Automatic (S8),NaN,SIDI,T,S,Premium,...,NaN,NaN,N,Y,NaN,NaN,VVX,NaN,NaN,NaN
38110,Volvo,XC90 AWD,Standard Sport Utility Vehicle 4WD,All-Wheel Drive,Automatic (S8),NaN,SIDI,T,NaN,Premium,...,NaN,NaN,N,Y,NaN,NaN,VVX,NaN,NaN,NaN
38111,Volvo,XC90 AWD PHEV,Standard Sport Utility Vehicle 4WD,All-Wheel Drive,Automatic (S8),NaN,SIDI; PHEV,T,S,Premium and Electricity,...,Electricity,NaN,N,Y,Plug-in Hybrid,34 and 65kW DCPM,VVX,NaN,NaN,14
38112,Volvo,XC90 FWD,Standard Sport Utility Vehicle 2WD,Front-Wheel Drive,Automatic (S8),NaN,SIDI,T,NaN,Premium,...,NaN,NaN,N,Y,NaN,NaN,VVX,NaN,NaN,NaN

In [13]:
#i'm going to convert a few columns, Vehicle ID for example doesn't need to be a numeric. We would't do mathematical operations on ID
df['Vehicle ID']=df['Vehicle ID'].astype('category')
df

,Vehicle ID,Year,Make,Model,Class,Drive,Transmission,Transmission Descriptor,Engine Index,Engine Descriptor,...,Hours to Charge (AC 240V),Composite City MPG,Composite Highway MPG,Composite Combined MPG,Range (FT1),City Range (FT1),Highway Range (FT1),Range (FT2),City Range (FT2),Highway Range (FT2)
0,26587,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,NaN,Manual 5-Speed,NaN,9001,(FFS),...,0.0,0,0,0,0,0.0,0.0,NaN,0.00,0.0
1,27705,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,NaN,Manual 5-Speed,NaN,9005,(FFS) CA model,...,0.0,0,0,0,0,0.0,0.0,NaN,0.00,0.0
2,26561,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,NaN,Manual 5-Speed,NaN,9002,(FFS),...,0.0,0,0,0,0,0.0,0.0,NaN,0.00,0.0
3,27681,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,NaN,Manual 5-Speed,NaN,9006,(FFS) CA model,...,0.0,0,0,0,0,0.0,0.0,NaN,0.00,0.0
4,27550,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,2-Wheel Drive,Automatic 3-Speed,NaN,1830,(FFS),...,0.0,0,0,0,0,0.0,0.0,NaN,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38108,37564,2017,Volvo,XC60 FWD,Small Sport Utility Vehicle 2WD,Front-Wheel Drive,Automatic (S8),NaN,90,SIDI,...,0.0,0,0,0,0,0.0,0.0,NaN,0.00,0.0
38109,37547,2017,Volvo,XC90 AWD,Standard Sport Utility Vehicle 4WD,All-Wheel Drive,Automatic (S8),NaN,52,SIDI,...,0.0,0,0,0,0,0.0,0.0,NaN,0.00,0.0
38110,37548,2017,Volvo,XC90 AWD,Standard Sport Utility Vehicle 4WD,All-Wheel Drive,Automatic (S8),NaN,53,SIDI,...,0.0,0,0,0,0,0.0,0.0,NaN,0.00,0.0
38111,37703,2017,Volvo,XC90 AWD PHEV,Standard Sport Utility Vehicle 4WD,All-Wheel Drive,Automatic (S8),NaN,54,SIDI; PHEV,...,0.0,29,32,30,0,0.0,0.0,14,13.84,13.3
38112,37687,2017,Volvo,XC90 FWD,Standard Sport Utility Vehicle 2WD,Front-Wheel Drive,Automatic (S8),NaN,50,SIDI,...,0.0,0,0,0,0,0.0,0.0,NaN,0.00,0.0

In [16]:
#summary statistics for all numerical columns
df.describe()

,Year,Engine Index,Engine Cylinders,Engine Displacement,City MPG (FT1),Unrounded City MPG (FT1),City MPG (FT2),Unrounded City MPG (FT2),City Gasoline Consumption (CD),City Electricity Consumption,...,Hours to Charge (240V),Hours to Charge (AC 240V),Composite City MPG,Composite Highway MPG,Composite Combined MPG,Range (FT1),City Range (FT1),Highway Range (FT1),City Range (FT2),Highway Range (FT2)
count,38113.000000,38113.000000,37977.000000,37979.000000,38113.000000,38113.000000,38113.000000,38113.000000,38113.000000,38113.000000,...,38113.000000,38113.000000,38113.000000,38113.000000,38113.000000,38113.000000,38113.000000,38113.000000,38113.000000,38113.000000
mean,2000.194527,8799.389001,5.736656,3.317583,17.981109,4.606426,0.546218,0.386633,0.000432,0.205802,...,0.027635,0.005549,0.082203,0.080891,0.081311,0.469708,0.426249,0.419197,0.043973,0.040051
std,10.464573,17781.058490,1.752254,1.361995,6.849728,10.113963,4.109282,3.861179,0.039976,3.043951,...,0.473685,0.161014,2.156682,2.052187,2.097794,9.352069,9.104702,9.315914,1.311628,1.169281
min,1984.000000,0.000000,2.000000,0.000000,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1991.000000,0.000000,4.000000,2.200000,15.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2001.000000,212.000000,6.000000,3.000000,17.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,2009.000000,4451.000000,6.000000,4.300000,20.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,2017.000000,69102.000000,16.000000,8.400000,150.000000,150.000000,145.000000,145.083500,5.350000,122.000000,...,12.000000,7.000000,97.000000,81.000000,88.000000,315.000000,305.900000,346.900000,103.030000,90.550000

In [17]:
#now i'll interpret the Combined MPG column
mean_mpg=df['Combined MPG (FT1)'].mean()
print(f'The average combined MPG for all vehicles is: {mean_mpg:.2f}')

The average combined MPG for all vehicles is: 20.22

The descriptive summary helps us better understand our numerical columns. For example, the mean I calculated in the above cell tells me hat the average car gets around 20 miles/gallon across all the years. I didn't see any columns where the values seemed unusual or inconsistent. There are a lot of 0s because there is a lot of missing data, and I expected this.

In [18]:
df.isnull().sum()[df.isnull().sum() > 0] #this shows us the columns that have null values > 0

Drive                           1189
Transmission                      11
Transmission Descriptor        23068
Engine Descriptor              15420
Engine Cylinders                 136
Engine Displacement              134
Turbocharger                   32874
Supercharger                   37420
Fuel Type 2                    36675
Gas Guzzler Tax                35817
Start Stop Technology          31670
Alternative Fuel/Technology    35066
Electric Motor                 37509
Manufacturer Code              30794
Vehicle Charger                38065
Alternate Charger              38067
Range (FT2)                    36680
dtype: int64

In [19]:
df.isnull().sum()[df.isnull().sum() > 0]/len(df)*100 # % of missing values

Drive                           3.119670
Transmission                    0.028862
Transmission Descriptor        60.525280
Engine Descriptor              40.458636
Engine Cylinders                0.356834
Engine Displacement             0.351586
Turbocharger                   86.254034
Supercharger                   98.181723
Fuel Type 2                    96.227009
Gas Guzzler Tax                93.975809
Start Stop Technology          83.095007
Alternative Fuel/Technology    92.005353
Electric Motor                 98.415239
Manufacturer Code              80.796579
Vehicle Charger                99.874059
Alternate Charger              99.879306
Range (FT2)                    96.240128
dtype: float64

In [20]:
df_new=df.copy()

In [23]:
threshold = 50
missing_percent=(df_new.isnull().sum()/len(df_new))*100
cols_to_drop=missing_percent[missing_percent > threshold].index
df_new=df_new.drop(columns=cols_to_drop)
df_new

,Vehicle ID,Year,Make,Model,Class,Drive,Transmission,Engine Index,Engine Descriptor,Engine Cylinders,...,Hours to Charge (240V),Hours to Charge (AC 240V),Composite City MPG,Composite Highway MPG,Composite Combined MPG,Range (FT1),City Range (FT1),Highway Range (FT1),City Range (FT2),Highway Range (FT2)
0,26587,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,NaN,Manual 5-Speed,9001,(FFS),6.0,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0
1,27705,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,NaN,Manual 5-Speed,9005,(FFS) CA model,6.0,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0
2,26561,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,NaN,Manual 5-Speed,9002,(FFS),4.0,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0
3,27681,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,NaN,Manual 5-Speed,9006,(FFS) CA model,4.0,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0
4,27550,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,2-Wheel Drive,Automatic 3-Speed,1830,(FFS),4.0,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38108,37564,2017,Volvo,XC60 FWD,Small Sport Utility Vehicle 2WD,Front-Wheel Drive,Automatic (S8),90,SIDI,4.0,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0
38109,37547,2017,Volvo,XC90 AWD,Standard Sport Utility Vehicle 4WD,All-Wheel Drive,Automatic (S8),52,SIDI,4.0,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0
38110,37548,2017,Volvo,XC90 AWD,Standard Sport Utility Vehicle 4WD,All-Wheel Drive,Automatic (S8),53,SIDI,4.0,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0
38111,37703,2017,Volvo,XC90 AWD PHEV,Standard Sport Utility Vehicle 4WD,All-Wheel Drive,Automatic (S8),54,SIDI; PHEV,4.0,...,3.0,0.0,29,32,30,0,0.0,0.0,13.84,13.3
38112,37687,2017,Volvo,XC90 FWD,Standard Sport Utility Vehicle 2WD,Front-Wheel Drive,Automatic (S8),50,SIDI,4.0,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0

In [24]:
df_new.isnull().sum()[df_new.isnull().sum() > 0]

Drive                   1189
Transmission              11
Engine Descriptor      15420
Engine Cylinders         136
Engine Displacement      134
dtype: int64

In [25]:
print(df_new[df_new['Engine Cylinders'].isnull()]['Fuel Type'].unique())

['Regular' 'Electricity']

In [26]:
df_new.loc[df_new['Fuel Type'] == 'Electricity', 'Engine Cylinders'] = 0
df_new.loc[df_new['Fuel Type'] == 'Electricity', 'Engine Displacement'] = 0
df_new

,Vehicle ID,Year,Make,Model,Class,Drive,Transmission,Engine Index,Engine Descriptor,Engine Cylinders,...,Hours to Charge (240V),Hours to Charge (AC 240V),Composite City MPG,Composite Highway MPG,Composite Combined MPG,Range (FT1),City Range (FT1),Highway Range (FT1),City Range (FT2),Highway Range (FT2)
0,26587,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,NaN,Manual 5-Speed,9001,(FFS),6.0,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0
1,27705,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,NaN,Manual 5-Speed,9005,(FFS) CA model,6.0,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0
2,26561,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,NaN,Manual 5-Speed,9002,(FFS),4.0,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0
3,27681,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,NaN,Manual 5-Speed,9006,(FFS) CA model,4.0,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0
4,27550,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,2-Wheel Drive,Automatic 3-Speed,1830,(FFS),4.0,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38108,37564,2017,Volvo,XC60 FWD,Small Sport Utility Vehicle 2WD,Front-Wheel Drive,Automatic (S8),90,SIDI,4.0,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0
38109,37547,2017,Volvo,XC90 AWD,Standard Sport Utility Vehicle 4WD,All-Wheel Drive,Automatic (S8),52,SIDI,4.0,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0
38110,37548,2017,Volvo,XC90 AWD,Standard Sport Utility Vehicle 4WD,All-Wheel Drive,Automatic (S8),53,SIDI,4.0,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0
38111,37703,2017,Volvo,XC90 AWD PHEV,Standard Sport Utility Vehicle 4WD,All-Wheel Drive,Automatic (S8),54,SIDI; PHEV,4.0,...,3.0,0.0,29,32,30,0,0.0,0.0,13.84,13.3
38112,37687,2017,Volvo,XC90 FWD,Standard Sport Utility Vehicle 2WD,Front-Wheel Drive,Automatic (S8),50,SIDI,4.0,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0

In [27]:
#because these columns are numerical, i can input the median for the missing values of non-electric vehicles and this will keep the distribution stable
df_new['Engine Cylinders']=df_new['Engine Cylinders'].fillna(df['Engine Cylinders'].median())
df_new['Engine Displacement']=df_new['Engine Displacement'].fillna(df['Engine Displacement'].median())
df_new

,Vehicle ID,Year,Make,Model,Class,Drive,Transmission,Engine Index,Engine Descriptor,Engine Cylinders,...,Hours to Charge (240V),Hours to Charge (AC 240V),Composite City MPG,Composite Highway MPG,Composite Combined MPG,Range (FT1),City Range (FT1),Highway Range (FT1),City Range (FT2),Highway Range (FT2)
0,26587,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,NaN,Manual 5-Speed,9001,(FFS),6.0,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0
1,27705,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,NaN,Manual 5-Speed,9005,(FFS) CA model,6.0,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0
2,26561,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,NaN,Manual 5-Speed,9002,(FFS),4.0,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0
3,27681,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,NaN,Manual 5-Speed,9006,(FFS) CA model,4.0,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0
4,27550,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,2-Wheel Drive,Automatic 3-Speed,1830,(FFS),4.0,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38108,37564,2017,Volvo,XC60 FWD,Small Sport Utility Vehicle 2WD,Front-Wheel Drive,Automatic (S8),90,SIDI,4.0,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0
38109,37547,2017,Volvo,XC90 AWD,Standard Sport Utility Vehicle 4WD,All-Wheel Drive,Automatic (S8),52,SIDI,4.0,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0
38110,37548,2017,Volvo,XC90 AWD,Standard Sport Utility Vehicle 4WD,All-Wheel Drive,Automatic (S8),53,SIDI,4.0,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0
38111,37703,2017,Volvo,XC90 AWD PHEV,Standard Sport Utility Vehicle 4WD,All-Wheel Drive,Automatic (S8),54,SIDI; PHEV,4.0,...,3.0,0.0,29,32,30,0,0.0,0.0,13.84,13.3
38112,37687,2017,Volvo,XC90 FWD,Standard Sport Utility Vehicle 2WD,Front-Wheel Drive,Automatic (S8),50,SIDI,4.0,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0

In [28]:
#i'm going to label the missing categorical values with "unknown"
df_new['Drive']=df_new['Drive'].fillna('Unknown')
df_new['Transmission']=df_new['Transmission'].fillna('Unknown')
df_new['Engine Descriptor']=df_new['Engine Descriptor'].fillna('Unknown')
df_new

,Vehicle ID,Year,Make,Model,Class,Drive,Transmission,Engine Index,Engine Descriptor,Engine Cylinders,...,Hours to Charge (240V),Hours to Charge (AC 240V),Composite City MPG,Composite Highway MPG,Composite Combined MPG,Range (FT1),City Range (FT1),Highway Range (FT1),City Range (FT2),Highway Range (FT2)
0,26587,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,Unknown,Manual 5-Speed,9001,(FFS),6.0,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0
1,27705,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,Unknown,Manual 5-Speed,9005,(FFS) CA model,6.0,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0
2,26561,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,Unknown,Manual 5-Speed,9002,(FFS),4.0,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0
3,27681,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,Unknown,Manual 5-Speed,9006,(FFS) CA model,4.0,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0
4,27550,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,2-Wheel Drive,Automatic 3-Speed,1830,(FFS),4.0,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38108,37564,2017,Volvo,XC60 FWD,Small Sport Utility Vehicle 2WD,Front-Wheel Drive,Automatic (S8),90,SIDI,4.0,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0
38109,37547,2017,Volvo,XC90 AWD,Standard Sport Utility Vehicle 4WD,All-Wheel Drive,Automatic (S8),52,SIDI,4.0,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0
38110,37548,2017,Volvo,XC90 AWD,Standard Sport Utility Vehicle 4WD,All-Wheel Drive,Automatic (S8),53,SIDI,4.0,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0
38111,37703,2017,Volvo,XC90 AWD PHEV,Standard Sport Utility Vehicle 4WD,All-Wheel Drive,Automatic (S8),54,SIDI; PHEV,4.0,...,3.0,0.0,29,32,30,0,0.0,0.0,13.84,13.3
38112,37687,2017,Volvo,XC90 FWD,Standard Sport Utility Vehicle 2WD,Front-Wheel Drive,Automatic (S8),50,SIDI,4.0,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0

I referenced the notebook that you provided us with to better clean the data. The columns that were dropped would've interfered with my analysis because they had a large percent of missing values that would have been difficult to work with. The columns that I filled with the median and 'unknown' were also for ease of analysis. It would've been harder to use the dataset otherwise.

In [29]:
df_new.duplicated().sum()

np.int64(0)

In [32]:
#i'm going to add a column of cost per mile, i think this will help identify the most cost-efficient cars
df_new['Cost Per Mile']=df_new['Annual Fuel Cost (FT1)']/15000
print(df_new[['Make', 'Model','Cost Per Mile']].head())

         Make               Model  Cost Per Mile
0  Alfa Romeo           GT V6 2.5       0.116667
1  Alfa Romeo           GT V6 2.5       0.116667
2  Alfa Romeo  Spider Veloce 2000       0.110000
3  Alfa Romeo  Spider Veloce 2000       0.110000
4  AM General   DJ Po Vehicle 2WD       0.136667

In [36]:
#curious about seeing the high efficiency vehicles in 2017
df_filtered=df_new[(df_new['Year'] == 2017)& (df_new['Combined MPG (FT1)'] > 30)]
print(df_filtered[['Make', 'Model', 'Year', 'Combined MPG (FT1)']])

             Make                     Model  Year  Combined MPG (FT1)
36909        Audi                 A3 e-tron  2017                  34
36915        Audi                  A4 Ultra  2017                  31
36962         BMW                      328d  2017                  36
36963         BMW               328d xDrive  2017                  34
36964         BMW  328d xDrive Sports Wagon  2017                  34
...           ...                       ...   ...                 ...
38059      Toyota                     Yaris  2017                  33
38060      Toyota                  Yaris iA  2017                  35
38061      Toyota                  Yaris iA  2017                  34
38082  Volkswagen                     Jetta  2017                  32
38084  Volkswagen                     Jetta  2017                  33

[144 rows x 4 columns]

In [39]:
#unique values of a categorical column
print(df_new['Drive'].unique())

['Unknown' '2-Wheel Drive' '4-Wheel or All-Wheel Drive' 'Rear-Wheel Drive'
 'Front-Wheel Drive' '4-Wheel Drive' 'All-Wheel Drive'
 'Part-time 4-Wheel Drive']

Because we're interested in seeing the most efficient vehicle, categorical columns like Make, Model, Drive, Fuel Type would be important for our analysis

In [43]:
make_grouping=df_new.groupby('Make')['Combined MPG (FT1)'].mean()
make_grouping=make_grouping.sort_values(ascending=False)
detailed=df_new.groupby('Make')['Combined MPG (FT1)'].agg(['mean', 'count', 'max'])
print(detailed.sort_values(by='mean', ascending=False).head(10))

                      mean  count  max
Make
Tesla            94.452381     42  104
CODA Automotive  73.000000      2   73
BYD              65.000000      4   72
Azure Dynamics   62.000000      2   62
smart            56.656250     32  107
Fiat             37.137255     51  116
Daihatsu         29.647059     17   34
Grumman Olson    28.750000      4   31
MINI             28.379205    327   98
Scion            28.190476     84  121

This grouping helped me extract more specific data from the dataset. By grouping by Make, I was able to see that electric/hybrid manufacturers usually display the highest average fuel economies.

In [45]:
#the car with the highest MPG
best_car=df_new.loc[df_new['Combined MPG (FT1)'].idxmax()]
print(f'The most efficient vehicle is the {best_car['Year']} {best_car['Make']} {best_car['Model']}.')

The most efficient vehicle is the 2017 Hyundai Ioniq Electric.

In [46]:
df_new.to_csv('cleaned_fuel_economy_dataset.csv', index=False)

In [47]:
pd.read_csv('cleaned_fuel_economy_dataset.csv')

,Vehicle ID,Year,Make,Model,Class,Drive,Transmission,Engine Index,Engine Descriptor,Engine Cylinders,...,Hours to Charge (AC 240V),Composite City MPG,Composite Highway MPG,Composite Combined MPG,Range (FT1),City Range (FT1),Highway Range (FT1),City Range (FT2),Highway Range (FT2),Cost Per Mile
0,26587,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,Unknown,Manual 5-Speed,9001,(FFS),6.0,...,0.0,0,0,0,0,0.0,0.0,0.00,0.0,0.116667
1,27705,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,Unknown,Manual 5-Speed,9005,(FFS) CA model,6.0,...,0.0,0,0,0,0,0.0,0.0,0.00,0.0,0.116667
2,26561,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,Unknown,Manual 5-Speed,9002,(FFS),4.0,...,0.0,0,0,0,0,0.0,0.0,0.00,0.0,0.110000
3,27681,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,Unknown,Manual 5-Speed,9006,(FFS) CA model,4.0,...,0.0,0,0,0,0,0.0,0.0,0.00,0.0,0.110000
4,27550,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,2-Wheel Drive,Automatic 3-Speed,1830,(FFS),4.0,...,0.0,0,0,0,0,0.0,0.0,0.00,0.0,0.136667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38108,37564,2017,Volvo,XC60 FWD,Small Sport Utility Vehicle 2WD,Front-Wheel Drive,Automatic (S8),90,SIDI,4.0,...,0.0,0,0,0,0,0.0,0.0,0.00,0.0,0.090000
38109,37547,2017,Volvo,XC90 AWD,Standard Sport Utility Vehicle 4WD,All-Wheel Drive,Automatic (S8),52,SIDI,4.0,...,0.0,0,0,0,0,0.0,0.0,0.00,0.0,0.126667
38110,37548,2017,Volvo,XC90 AWD,Standard Sport Utility Vehicle 4WD,All-Wheel Drive,Automatic (S8),53,SIDI,4.0,...,0.0,0,0,0,0,0.0,0.0,0.00,0.0,0.123333
38111,37703,2017,Volvo,XC90 AWD PHEV,Standard Sport Utility Vehicle 4WD,All-Wheel Drive,Automatic (S8),54,SIDI; PHEV,4.0,...,0.0,29,32,30,0,0.0,0.0,13.84,13.3,0.113333
38112,37687,2017,Volvo,XC90 FWD,Standard Sport Utility Vehicle 2WD,Front-Wheel Drive,Automatic (S8),50,SIDI,4.0,...,0.0,0,0,0,0,0.0,0.0,0.00,0.0,0.116667

I really liked working with this dataset. I found it pretty challenging at first, but the notebook you provided us with helped me better understand how I need to clean sets with extensive missing values. When we first started our analysis, I wasnt't expecting to notice that electric vehicles seem to perform better with higher Combined MPGs, this was an interesting trend to observe. I also liked this dataset because it has relevant real-world applications. These are important things for possible buyers to be aware of, and this helped highlight how data science can help us in everyday life. I had some issues with cleaning and grouping, but there were plenty of resources to help me figure out what I needed to do. I'm really excited to see what we do next!